version: '3.7'

services:
  apiserver:
    build:
      context: ../../
      dockerfile: apiserver/cmd/Dockerfile
    ports:
      - "19089:19089"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
      - RUN_PORT=:19089
      - VIRTUAL_MACHINE_URL=http://172.28.1.2:19088
      - LISTEN_ADDR=http://172.28.1.1:9999
      - TEMP_DIR=/app/data # 跟virtualmachine的volume挂载目录一致
    depends_on:
      - virtualmachine
    networks:
      wxhelper: # FIXME 在wine中无法使用服务名解析，所以需要使用固定ip
        ipv4_address: 172.28.1.1
    volumes:
      - ./data/wechat:/app/data

  virtualmachine:
    image: lxh01/wxhelper-docker:3.9.5.81-v11
    container_name: virtualmachine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    environment:
      - WINEDEBUG=fixme-all
    volumes:
      - ./data/wechat:/home/app/.wine/drive_c/data
    networks:
      wxhelper:
        ipv4_address: 172.28.1.2

#  redis:
#    image: redis:alpine
#    container_name: redis
#    restart: unless-stopped
#    volumes:
#      - ./data/redis:/data

networks:
  wxhelper:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16