version: '3.8'

services:
  apiserver:
    build:
      context: ../../
      dockerfile: apiserver/cmd/Dockerfile
    ports:
      - "19089:19089"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
      - PORT=19089
      - VIRTUAL_MACHINE_URL=http://virtualmachine:19088

  virtualmachine:
    image: lxh01/wxhelper-docker:3.9.5.81-v11
    container_name: virtualmachine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"

