version: '3.7'

services:
  apiserver:
    build:
      context: ../../
      dockerfile: apiserver/cmd/Dockerfile
    ports:
      - "19089:19089"
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
      - RUN_PORT=:19089
      - VIRTUAL_MACHINE_URL=http://virtualmachine:19088
      - TEMP_DIR=/app/data # 跟virtualmachine的volume挂载目录一致
      - MSG_QUEUE_ADDR=redis:6379 # redis 消息队列地址
    depends_on:
      - virtualmachine
      - redis
    volumes:
      - ./data/data:/app/data

  virtualmachine:
    image: lxh01/wxhelper-docker:3.9.5.81-v11
    container_name: virtualmachine
    restart: unless-stopped
    user: "1000:1000"
    tty: true
    ports:
      - "8080:8080"
    environment:
      - WINEDEBUG=fixme-all
    volumes:
      - ./data/data:/home/app/.wine/drive_c/data
      - ./data/wechat:/home/app/.wine/drive_c/users/app/Documents/WeChat\ Files
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:19088/api/checkLogin" ]
      interval: 30s
      timeout: 20s # 一般是20s旁边完成注入
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data